FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Устанавливаем системные зависимости для компиляции C++ и работы с Postgres
RUN apt-get update

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --default-timeout=100 --no-cache-dir \
    -i https://pypi.org/simple \
    --extra-index-url https://mirror.yandex.ru/pypi/simple \
    -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]