"""empty message

Revision ID: c7ce7bffd71f
Revises: 9f3d76418c72
Create Date: 2026-06-25 22:39:20.987352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ce7bffd71f'
down_revision: Union[str, None] = '9f3d76418c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'is_completed')
    # ### end Alembic commands ###
